### ISSUE TITLE
More tiles are visible than actually should be

### ISSUE THREAD

**Issue by constantinius** [EOEPCA/rm-data-access#5]
<img width="1053" alt="Bildschirmfoto 2020-12-23 um 11 11 07" src="https://user-images.githubusercontent.com/1109799/102985589-af220380-450f-11eb-929a-56605aaceb30.png">

**Comment by Schpidi** [comment]
Should be resolved with https://github.com/MapServer/mapcache/issues/246. Please reopen if still observed.
